
CREATE TABLE clock (
	id UUID NOT NULL, 
	step_size NUMERIC NOT NULL, 
	window_size INTEGER NOT NULL, 
	head TIMESTAMP WITH TIME ZONE NOT NULL, 
	tail TIMESTAMP WITH TIME ZONE NOT NULL, 
	y_size INTEGER NOT NULL, 
	y_pred TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (id)
)

